language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false
        - PACKAGE="mirage-unix"
        - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
    matrix:
        - OCAML_VERSION=4.07
        - OCAML_VERSION=4.06
        - OCAML_VERSION=4.05
        - OCAML_VERSION=4.04
